### ISSUE TITLE
RFR数据集问题

### ISSUE THREAD

**Issue by MOCUISHLE-AC** [XinyiYing/RFR#1]
您好，我关注了您RFR的工作，十分感谢您的贡献。但是复现您代码的时候出现了以下疑惑，期待您的答疑解惑。
（1）img_idx 下的txt 文件没有换行，导致dataloader错误，如下图所示：

![image](https://github.com/user-attachments/assets/1a48acc2-8e71-4790-aa8d-131df05c49bc)

（2）dataset.py中，module 导入的问题，没有这个module，我这里直接注释了，不知道可不可行。

![image](https://github.com/user-attachments/assets/14a695ae-41c1-4669-9380-fadd5f04d175)

PS：如果数据集没有别的改动的话，想请问您是否能将img_idx 文件夹直接更新在github上，实在是不想再下载一次数据集了。谢谢您，期待您的回复。

**Comment by XinyiYing** [comment]
1. img_idx 下的txt 文件已更新，下载链接见[https://pan.baidu.com/s/1MvOCx6VpqmvM6-0DfSfC0A?pwd=1113](https://pan.baidu.com/s/1MvOCx6VpqmvM6-0DfSfC0A?pwd=1113) 。
主页数据链接部分近期也会更新
2. 删去注释的话即可，已经更新了这个问题

**Comment by ntgoaywh** [comment]
> 您好，我关注了您RFR的工作，十分感谢您的贡献。但是复现您代码的时候出现了以下疑惑，期待您的答疑解惑。 （1）img_idx 下的txt 文件没有换行，导致dataloader错误，如下图所示：
> 
> ![image](https://github.com/user-attachments/assets/1a48acc2-8e71-4790-aa8d-131df05c49bc)
> 
> （2）dataset.py中，module 导入的问题，没有这个module，我这里直接注释了，不知道可不可行。
> 
> ![image](https://github.com/user-attachments/assets/14a695ae-41c1-4669-9380-fadd5f04d175)
> 
> PS：如果数据集没有别的改动的话，想请问您是否能将img_idx 文件夹直接更新在github上，实在是不想再下载一次数据集了。谢谢您，期待您的回复。

你好，我现在也出现了问题一，数据集下的img_idx文件夹仍然是没有换行的txt文件，我想问下你这边有更新过的文件吗

**Comment by XinyiYing** [comment]
（1）为了防止链接失效，img_idx和video_idx我直接上传“codes/data/”
（2）我看了dataset.py里面已经删去"from SIFT_module import *"
